CREATE DATABASE [Cinema Ticket Booking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Cinema Ticket Booking', FILENAME = N'/var/opt/mssql/data/Cinema Ticket Booking.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Cinema Ticket Booking_log', FILENAME = N'/var/opt/mssql/data/Cinema Ticket Booking_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 COLLATE SQL_Latin1_General_CP1_CI_AS
 WITH LEDGER = OFF
GO
ALTER DATABASE [Cinema Ticket Booking] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [Cinema Ticket Booking] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET ARITHABORT OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET AUTO_CREATE_STATISTICS OFF
GO
ALTER DATABASE [Cinema Ticket Booking] SET AUTO_UPDATE_STATISTICS OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Cinema Ticket Booking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Cinema Ticket Booking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Cinema Ticket Booking] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Cinema Ticket Booking] SET  READ_WRITE 
GO
ALTER DATABASE [Cinema Ticket Booking] SET RECOVERY FULL 
GO
ALTER DATABASE [Cinema Ticket Booking] SET  MULTI_USER 
GO
ALTER DATABASE [Cinema Ticket Booking] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [Cinema Ticket Booking] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Cinema Ticket Booking] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Cinema Ticket Booking]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Cinema Ticket Booking] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
